### ISSUE TITLE
getkey not working on mac

### ISSUE THREAD

**Issue by russlamb** [magmax/python-readchar#29]
My code is like this

```

import readchar

def console_loop():
    while True:
        key = readchar.readkey()
        print(key)

def main():
    console_loop()
```

I get the following error.

```
Traceback (most recent call last):
  File "/Users/current_user/Dropbox/Coding/Python/current_project/main.py", line 19, in <module>
    main()
  File "/Users/current_user/Dropbox/Coding/Python/current_project/main.py", line 11, in main
    console_loop()
  File "/Users/current_user/Dropbox/Coding/Python/current_project/main.py", line 7, in console_loop
    key = readchar.readkey()
  File "/Users/current_user/.virtualenvs/current_project/lib/python3.5/site-packages/readchar/readchar.py", line 20, in readkey
    c1 = getchar()
  File "/Users/current_user/.virtualenvs/current_project/lib/python3.5/site-packages/readchar/readchar_linux.py", line 12, in readchar
    old_settings = termios.tcgetattr(fd)
termios.error: (25, 'Inappropriate ioctl for device')

```

**Comment by russlamb** [comment]
i installed readchar-0.7 using pip

**Comment by felzix** [comment]
I think this should be closed because I am running mac with readchar==2.0.1 and it works fine.
