### ISSUE TITLE
 distutils.errors.DistutilsOptionError: find_namespace: directive is unsupported on Python < 3.3

### ISSUE THREAD

**Issue by custom-build-robots** [magmax/python-readchar#67]
I tried to install readchar via `sudo pip install readchar` on my Raspberry Pi but I got the following error `Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Qsyv9t/readchar/`

I tried to use several Raspberry Pi Operating systems from very old ones and the latest one. But independent of the version I use as OS I get the error message and I am not able to install readchar at all.
**Images I tried:**
- 2021-12-02-raspios-buster-armhf.img
- 2019-09-26-raspbian-buster-full.img
- 2020-02-13-raspbian-buster-full.img
- 2021-10-30-raspios-bullseye-armhf-full.img

**Actual used operating system on my Raspberry Pi:**
`pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
`

**Error message:**
pi@raspberrypi:~ $ sudo pip install readchar
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting readchar
  Using cached https://files.pythonhosted.org/packages/16/2b/0cd0ba53d6dcdc4d69dcff68970c9b1347cc1d7f1c17ed4c15ec3a71a6e5/readchar-3.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Qsyv9t/readchar/setup.py", line 85, in <module>
        "flake8",
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 704, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 730, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 915, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1169, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-FGr_SR/importlib_metadata-4.2.0/setup.py", line 6, in <module>

      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
        dist.parse_config_files()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 705, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 115, in parse_configuration
        options.parse()
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 425, in parse
        section_parser_method(section_options)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 398, in parse_section
        self[name] = value
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 183, in __setitem__
        value = parser(value)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 574, in _parse_packages
        'find_namespace: directive is unsupported on Python < 3.3')
    distutils.errors.DistutilsOptionError: find_namespace: directive is unsupported on Python < 3.3

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Qsyv9t/readchar/

**Python version:**
`pi@raspberrypi:~ $ python --version
Python 2.7.16
`

**My speculation:**
Maybe the error is thrown by a name spaces problem?

Thank you very much for your support,

Ingmar

**Comment by Cube707** [comment]
you are using python 2.7, which is, while its still listed, no longer tested as far as I am aware
